### ISSUE TITLE
Installing not possible

### ISSUE THREAD

**Issue by JulioCHS** [DanielMartensson/MataveControl#2]
Hi,

I tried the procedure for installing the package as shown on the description. However this didn't work, when I excecute the "savepath" command i get this:

warning: savepath: current path saved to ~\.octaverc

Do you have any idea ho can I do for getting the package working?

**Comment by bharris-fs** [comment]
I'm new to octave, so I can't explain why that's a warning, but I think it just means it remembered what you told it to do.  Look at your ~.octaverc.

At that point, I just tried the examples on the Readme page, and it just worked. I presume that means it is now a fixed part of my installation, not a package that requires loading with `pkg load sourcecode`, although I admit that's confusing to me.  Coming from an R background, I figured that I would have to load Matavecontrol in each new session. I had executed `pkg load control` in my octave session, and I presume I had a namespace issue from then on.  Closing that session and starting anew seemed to work.

**Comment by JulioCHS** [comment]
Hi,

Thanks for your feedback. I have two questions:
- Which version of Octave did you use?
- Is your Octave version a portable version or an Installed one?

Thanks for your help

**Comment by bharris-fs** [comment]
I'm running an installed Octave 4.0.3 on Debian Stable.

**Comment by JulioCHS** [comment]
Re-tested, It seems to be OK, my mistake I suppose. I close the issue.

**Comment by DanielMartensson** [comment]
Hello. 

Have I missed something? How can this issue be on my MataveID,
