### ISSUE TITLE
findstr is obsolete

### ISSUE THREAD

**Issue by griff10000** [DanielMartensson/MataveControl#3]
following warning when running tf() :
warning: findstr is obsolete; use strfind instead

**Comment by DanielMartensson** [comment]
> following warning when running tf() :
> warning: findstr is obsolete; use strfind instead

Can you show me an example?

**Comment by griff10000** [comment]
Line 136 of tf.m

if(length(findstr(char(polyString(1,i)), '-')) > 0)

**Comment by DanielMartensson** [comment]
> Line 136 of tf.m
> 
> if(length(findstr(char(polyString(1,i)), '-')) > 0)

Try to run the command "updatematavecontrol" twice now. 

```
>> G = tf([2 3], [3 5 2], 4)
G =

  scalar structure containing the fields:

    num =

       2   3

    den =

       3   5   2

    delay =  4
    tfnum =  2s + 3
    tfdash = --------------e^(-4s)
    tfden =  3s^2 + 5s + 2
    type = TF
    sampleTime = 0

>>
```

**Comment by griff10000** [comment]
I am not disputing this. The issue I am reporting is that Matlab function findstr() is now obsolete:

**Comment by DanielMartensson** [comment]
> I am not disputing this. The issue I am reporting is that Matlab function findstr() is now obsolete:

Thank you. I have fixed the warning now by replacing the command. I did also update the "updatematavecontrol" command.
